[buildpack]
id = "dreamfactory/dreamfactory"
version = "1.0.0"
name = "DreamFactory Buildpack"
homepage = "https://github.com/dreamfactorysoftware/df-herku-bp"

[metadata]
include-files = [
  "bin/",
  "lib/",
  "buildpack.toml",
  "README.md"
]

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22" 